version: '3'
services:
  public-token-db:
    image: postgres:13-buster
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=public-token-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=UTC
    volumes:
      - ~/postgresql/data/:/var/lib/postgresql/data
